# -*- coding: utf-8 -*-
"""Traitement de données de ventes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19_iBEssgPrQc1FDGz2oKWB36XNRPYZCh
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

url_data = "/content/train.csv"
df = pd.read_csv(url_data)
df.head(5)

"""#Explorer les données

"""

df.info() # résumé du DataFrame

df.describe() # stats descriptives

df.columns # noms des colonnes

df.shape # dimensions

"""# Nettoyage de base"""

#  Renommer les colonnes
df.rename(columns={
    'Row ID': 'ID Ligne',
    'Order ID': 'ID Commande',
    'Order Date': 'Date Commande',
    'Ship Date': 'Date Expedition',
    'Ship Mode': 'Mode Livraison',
    'Customer ID': 'ID Client',
    'Customer Name': 'Nom Client',
    'Segment': 'Segment Client',
    'Country': 'Pays',
    'City': 'Ville',
    'State': 'État',
    'Postal Code': 'Code Postal',
    'Region': 'Région',
    'Product ID': 'ID Produit',
    'Category': 'Catégorie',
    'Sub-Category': 'Sous-Catégorie',
    'Product Name': 'Nom Produit',
    'Sales': 'Ventes'
}, inplace=True)

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

df.head(5)

# Gérer les valeurs manquantes

df.isnull().sum()       # nombre de valeurs manquantes par colonne

"""Nous constatons que dans la colonne code postale il ya 11 valeurs manquantes , on va devoir les supprimer"""

df.dropna(inplace=True) # supprimer les lignes avec des valeurs manquantes
df.isnull().sum()

df.drop_duplicates(inplace=True)

df.duplicated() # lignes dupliquées

df["date_commande"].dtype

df["date_expédition"].dtype

"""Les dates ne sont pas au bon format, alors nous allons changer le types pour des dates


"""

df["date_expédition"] = pd.to_datetime(df["date_expédition"], format='%d/%m/%Y')
df["date_commande"] = pd.to_datetime(df["date_commande"], format='%d/%m/%Y')

print(df["date_expédition"].dtype)
print(df["date_commande"].dtype)

df

"""#Transformation des données

"""

# Extraire l'année, le mois, le jour

df["Année Commande"] = df["date_commande"].dt.year
df["Mois Commande"] = df["date_commande"].dt.month
df["Jour Commande"] = df["date_commande"].dt.day

# le délai de livraison

df["Délai Livraison"] = (df["date_expédition"] - df["date_commande"]).dt.days

df["Mois Commande"] = df["date_commande"].dt.strftime("%B %Y")

df.head(5)

"""# Créer un schéma en étoile"""

Dim_Lieu = df[['pays', 'ville', 'état', 'région', 'code_postal']].drop_duplicates().reset_index(drop=True)
Dim_Lieu['id_lieu'] = Dim_Lieu.index + 1  # Création d'un identifiant unique
Dim_Lieu.head(5)

# Merge pour ajouter id_lieu dans le DataFrame d'origine
df_lieu = df.merge(Dim_Lieu, on=['pays', 'ville', 'état', 'région', 'code_postal'], how='left')

Faits_Ventes = df_lieu[[
    'id_ligne', 'id_commande', 'id_client', 'id_produit',
    'date_commande', 'ventes', 'Délai Livraison', 'id_lieu'
]]


Faits_Ventes.head(5)

Dim_Temps = df[[
    'date_commande', 'Année Commande', 'Mois Commande', 'Jour Commande'
]].drop_duplicates().rename(columns={
    'date_commande': 'id_date',
    'Année Commande': 'année',
    'Mois Commande': 'mois',
    'Jour Commande': 'jour'
})
Dim_Temps.shape

Dim_Client = df_lieu[['id_client', 'nom_client', 'segment_client', 'id_lieu']].drop_duplicates()
Dim_Client.head(5)

Dim_Produit = df[['id_produit', 'nom_produit', 'catégorie', 'sous-catégorie']].drop_duplicates()

Dim_Commande = df[['id_commande', 'date_commande', 'date_expédition', 'mode_livraison','Délai Livraison']].drop_duplicates()

"""🧠 Résumé du schéma en étoile produit
Fait principal : Faits_Ventes (mesures : ventes, délai livraison)

Dimensions reliées :

Dim_Client

Dim_Produit

Dim_Lieu

Dim_Commande

Dim_Temps

# Exporter chaque table en CSV
"""

# Exporter chaque table en CSV
Dim_Lieu.to_csv("Dim_Lieu.csv", index=False)
df_lieu.to_csv("df_lieu.csv", index=False)
Faits_Ventes.to_csv("Faits_Ventes.csv", index=False)
Dim_Temps.to_csv("Dim_Temps.csv", index=False)
Dim_Client.to_csv("Dim_Client.csv", index=False)
Dim_Produit.to_csv("Dim_Produit.csv", index=False)
Dim_Commande.to_csv("Dim_Commande.csv", index=False)

# 2. Téléchargement automatique (pour Google Colab uniquement)
from google.colab import files

files.download("Dim_Lieu.csv")
files.download("df_lieu.csv")
files.download("Faits_Ventes.csv")
files.download("Dim_Temps.csv")
files.download("Dim_Client.csv")
files.download("Dim_Produit.csv")
files.download("Dim_Commande.csv")